### ISSUE TITLE
10% size reduction with one search & replace operation

### ISSUE THREAD

**Issue by jpeg729** [monarkee/beard#35]
In Geany I replaced `@media ([^{]*){([^{]*){([^}]*)}}@media \1{` with `@media \1{\2{\3}`.

Basically, if you look at the beautified code, you see the following pattern again and again.

```css
@media screen and (min-width: 30rem) {
    .sm-tal {
        text-align: left !important
    }
}
@media screen and (min-width: 30rem) {
    .sm-tac {
        text-align: center !important
    }
}
@media screen and (min-width: 30rem) {
    .sm-tar {
        text-align: right !important
    }
}
```
Clearly the second and third `@media` declarations could be merged with the first with no side-effects.
Geany replaced 577 occurrences and `beard.css` dropped from ~240kb to ~215kb.

I know it will be gzipped, but I imagine the cleaner version will be slightly lighter for the browser to work with once unzipped.
