### ISSUE TITLE
Add Split Module

### ISSUE THREAD

**Issue by davidhemphill** [monarkee/beard#5]
Something like this?

```scss
.split {
    display: flex;
}

.split__col {
    flex: 50%;
    margin-right: $basic-spacing;

    &:last-child {
        margin-right: 0;
    }
}
```
